[package]
name = "podrs"
version = "0.1.2"
authors = ["David Izquierdo <david@izquierdofernandez.com>"]

[dependencies]
hyper = "0.11"
reqwest = "0.8"
serde_derive = "1"
serde = "1"
serde-xml-rs = "0.2"
chrono = { version = "0.4", features = ["serde"] }
clap = "2"
